name: doorstop
title: Doorstop
version: '2.1.2'
summary: Requirements management using version control.
description: |
  Doorstop is a requirements management tool that facilitates the storage of
  textual requirements alongside source code in version control.
  
  When a project leverages this tool, each linkable item (requirement,
  test case, etc.) is stored as a YAML file in a designated directory.
  The items in each directory form a document. The relationship between
  documents forms a tree hierarchy. Doorstop provides mechanisms for modifying
  this tree, validating item traceability, and publishing documents in several
  formats.
grade: devel
icon: snap/gui/logo-black-white.png

base: core18
confinement: strict

apps:
  doorstop:
    command: bin/doorstop
    plugs:
      - home

parts:
  doorstop:
    plugin: python
    python-version: python3
    python-packages:
      - doorstop==2.1.2
